# Generated by Django 3.2.6 on 2021-08-05 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('disease', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('fees', models.PositiveIntegerField(default=500)),
                ('started_med_on_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
